# Checks srch _id

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('train2.csv')
df2 = pd.read_csv('test2.csv')

In [5]:
df2 = df2.rename(columns={'srch_id':'srch_id2'})

In [6]:
df2.columns

Index([u'Unnamed: 0', u'srch_id2', u'prop_country_id', u'year', u'month',
       u'prop_score', u'prop_location_score1', u'prop_location_score2',
       u'diff_hist_price', u'usd_diff', u'star_diff',
       u'srch_query_affinity_score', u'orig_destination_distance',
       u'prop_review_score', u'price_rank', u'stars_rank', u'score_rank',
       u'price_per_pers', u'random_bool', u'price_usd', u'total_price',
       u'nr_pers', u'prop_id_counts', u'comp2_rate', u'comp5_rate',
       u'comp8_rate', u'ndcg'],
      dtype='object')

In [9]:
df.srch_id.unique()

array([     1,      4,      6, ..., 332782, 332784, 332785], dtype=int64)

In [11]:
df2.srch_id2.unique()

array([     1,      3,      6, ..., 332785, 332786, 332787], dtype=int64)

In [13]:
df.srch_id.unique()

array([     1,      4,      6, ..., 332782, 332784, 332785], dtype=int64)

In [22]:
dfcommon = np.where(df.srch_id.unique().isin(df2.srch_id2.unique()), 1, 0)

AttributeError: 'numpy.ndarray' object has no attribute 'isin'

In [23]:
% timeit df['new'] = np.where(df['srch_id'].isin(df2['srch_id2']), 1, 0)

1 loop, best of 3: 404 ms per loop


In [24]:
df.new.value_counts()

1    2973825
0    1984522
Name: new, dtype: int64

In [25]:
% timeit df['sameyears'] = np.where(df['year'].isin(df2['year']), 1, 0)

1 loop, best of 3: 362 ms per loop


In [26]:
df.sameyears.value_counts()

1    4958347
Name: sameyears, dtype: int64